### PR TITLE
add paper

### PR DESCRIPTION
**Pull request by hriaz17**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@hriaz17 : please change this bib entry to point to the actual conference proceedings not arxiv.

**Comment by hriaz17** [comment]
the proceedings for LREC have not been published yet so that will have to wait.

**Comment by MihaiSurdeanu** [comment]
You can create the bib entry for that ahead of time. It’s fine.
I think people should cite the proceedings not arxiv.

**Comment by hriaz17** [comment]
updated to proceedings.

**Pull request merged**
